# Generated by Django 2.1 on 2018-02-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0003_student_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date',
            new_name='birth_date',
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.BooleanField(default=True),
        ),
    ]
